FROM golang:1.17.9-buster

# hadolint ignore=DL3027
RUN apt-get update \
    && apt install apt-transport-https bats build-essential curl gnupg2 jq lintian rpm rsync rubygems-integration ruby-dev ruby -qy \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# hadolint ignore=DL3028
RUN gem install --no-ri --no-rdoc --quiet rake fpm package_cloud

WORKDIR /src
